import type { Locale } from "@/types/api";

type HomeCopy = Record<string, string>;

// Confirmed Nuxt dictionaries, with the current deployed Christmas campaign
// copy overriding the older local Nuxt Easter snapshot.
const copies: Record<Locale, HomeCopy> = {
  "en": {
    "seasonalTitle": "A Christmas to Remember in Egypt",
    "seasonalDescription": "From the Pyramids to the Nile — Make This Season Unforgettable",
    "promoTitle": "Book any package tour and enjoy a FREE tour experience included at no extra cost!",
    "promoButton": "View Packages",
    "heroKicker": "Get started your",
    "heroTitle": "Exciting Journey With Us",
    "makeTripShort": "Make Trip",
    "findTripShort": "Find Trip",
    "rentCarShort": "Rent Car",
    "happyCustomer": "Happy customer",
    "yearsExperience": "Years of experience",
    "totalDestinations": "Total Destinations",
    "tripadvisorRating": "Rating in Tripadvisor",
    "whyTravelHeadingBefore": "Why ",
    "whyTravelHeadingEmphasis": "travel",
    "whyTravelHeadingAfter": " with",
    "whyTravelHeadingBrand": "Sun Pyramids Tours?",
    "whyTravelHappyTitle": "Happy customers",
    "whyTravelHappyStat": "100K+ travelers served",
    "whyTravelHappyDescription": "Trusted by guests from around the world for memorable private tours, Nile cruises and Egypt experiences.",
    "whyTravelExperienceTitle": "Years of experience",
    "whyTravelExperienceStat": "50+ years of expertise",
    "whyTravelExperienceDescription": "A long-standing local travel company creating tailored Egypt journeys with trusted service and deep destination knowledge.",
    "whyTravelDestinationsTitle": "Total destinations",
    "whyTravelDestinationsStat": "60+ destinations and experiences",
    "whyTravelDestinationsDescription": "From Cairo and Giza to Luxor, Aswan, the Red Sea and desert escapes, discover Egypt through diverse experiences.",
    "whyTravelTripadvisorTitle": "Tripadvisor rating",
    "whyTravelTripadvisorStat": "5.0 rating on Tripadvisor",
    "whyTravelTripadvisorDescription": "Highly rated for guest care, organization, expert guides and unforgettable travel moments across Egypt.",
    "popularTitle": "Popular Distination",
    "popularDescription": "Many very Exciting places for you to visit for the next trip",
    "recommended": "Recomanded",
    "oneDayFilter": "One Day",
    "multiDaysFilter": "Multi Days",
    "nileCruisesFilter": "Nile Cruises",
    "shoreExcursionsFilter": "Shore Excursion",
    "makeYourTrip": "Make Your Trip",
    "specialOffersTitle": "Special offers for you",
    "specialOffersDescription": "Find the right offer before it's too late",
    "howItWorks": "How it works ?",
    "howItWorksDescription": "Only three steps away from Egypt",
    "findingTitle": "Finding Trip",
    "findingDescription": "Select your favorite trip",
    "bookingTitle": "Booking",
    "bookingDescription": "Trip booking and payment",
    "enjoyTitle": "Enjoy",
    "enjoyDescription": "Start your Exciting Journey",
    "highlightsTitle": "Highlights of Egypt",
    "highlightsDescription": "Discover the most important landmarks in Egypt",
    "travelBlogs": "Our Travel Blogs",
    "galleryTitle": "Gallery of Exciting journeys",
    "galleryDescription": "Follow us on social media to see more Exciting journeys",
    "faqTitle": "Frequently Asked Questions",
    "needHelp": "Need help to Finding  your Trip?",
    "seeMore": "See more",
    "contactNow": "Contact Now",
    "whenTravelling": "When will you be traveling?",
    "exactTime": "Have An Exact Time",
    "approximateTime": "Have An Approximate Time",
    "notSureYet": "Not Sure Yet",
    "from": "From",
    "to": "To",
    "selectStartDate": "Select the start date of the trip",
    "selectEndDate": "Select the end date of the trip",
    "selectMonth": "Select Month",
    "selectExpectedMonth": "Select the expected month of the trip",
    "manyDays": "How Many Days",
    "where": "Where",
    "choosePlace": "Choose your favorite place in Egypt",
    "howLong": "How Long",
    "chooseDuration": "How many days do you stay in Egypt",
    "search": "Search",
    "tripType": "Type of Trip?",
    "oneWay": "One Way",
    "roundTrip": "Round Trip",
    "carHolder": "Car Holder",
    "choosePickup": "Choose Pick-Up Location",
    "dropoff": "Drop Off Location",
    "chooseDropoff": "Choose Drop-Off Location",
    "pickupDate": "Pick Up Date and time",
    "choosePickupDate": "Choose the time and date for Pick Up",
    "returnDate": "Return Date and Time",
    "chooseReturnDate": "Choose the time and date for Return",
    "sendRequest": "Send Request",
    "fullName": "Full Name",
    "nationality": "Nationality",
    "phone": "Phone",
    "upcomingEventsEyebrow": "Upcoming Events",
    "upcomingEventsTitle": "Top Upcoming Tourist Events and Occasions in Egypt",
    "upcomingEventsDescription": "Discover our latest scheduled events and join us for an unforgettable experience. Book your spot today!",
    "viewAllEvents": "View All Events",
    "countdownToday": "Today",
    "countdownTomorrow": "Tomorrow",
    "countdownInDays": "In {days} days",
    "previousEvents": "Previous events",
    "nextEvents": "Next events"
  },
  "fr": {
    "seasonalTitle": "Un Noël inoubliable en Égypte",
    "seasonalDescription": "Des Pyramides au Nil — Rendez cette période des fêtes inoubliable",
    "promoTitle": "Réservez n’importe quel forfait touristique et profitez d’une expérience de visite GRATUITE incluse sans frais supplémentaires !",
    "promoButton": "Voir les forfaits",
    "heroKicker": "Commencez votre",
    "heroTitle": "Voyage passionnant avec nous",
    "makeTripShort": "Organiser un voyage",
    "findTripShort": "Trouver un voyage",
    "rentCarShort": "Louer une voiture",
    "happyCustomer": "Client satisfait",
    "yearsExperience": "Années d'expérience",
    "totalDestinations": "Destinations totales",
    "tripadvisorRating": "Évaluation sur Tripadvisor",
    "whyTravelHeadingBefore": "Pourquoi ",
    "whyTravelHeadingEmphasis": "voyager",
    "whyTravelHeadingAfter": " avec",
    "whyTravelHeadingBrand": "Sun Pyramids Tours ?",
    "whyTravelHappyTitle": "Clients satisfaits",
    "whyTravelHappyStat": "Plus de 100 000 voyageurs accompagnés",
    "whyTravelHappyDescription": "Des voyageurs du monde entier nous font confiance pour des circuits privés, des croisières sur le Nil et des expériences mémorables en Égypte.",
    "whyTravelExperienceTitle": "Années d’expérience",
    "whyTravelExperienceStat": "Plus de 50 ans d’expertise",
    "whyTravelExperienceDescription": "Une agence de voyages locale de longue date, qui crée des séjours sur mesure en Égypte avec un service fiable et une connaissance approfondie des destinations.",
    "whyTravelDestinationsTitle": "Destinations",
    "whyTravelDestinationsStat": "Plus de 60 destinations et expériences",
    "whyTravelDestinationsDescription": "Du Caire et de Gizeh à Louxor, Assouan, la mer Rouge et aux escapades dans le désert, découvrez l’Égypte à travers des expériences variées.",
    "whyTravelTripadvisorTitle": "Note Tripadvisor",
    "whyTravelTripadvisorStat": "Note de 5,0 sur Tripadvisor",
    "whyTravelTripadvisorDescription": "Très bien notée pour l’attention portée aux voyageurs, l’organisation, ses guides experts et des moments de voyage inoubliables à travers l’Égypte.",
    "popularTitle": "Destinations populaires",
    "popularDescription": "De nombreux endroits passionnants à visiter pour votre prochain voyage",
    "recommended": "Recommandé",
    "oneDayFilter": "Une journée",
    "multiDaysFilter": "Plusieurs jours",
    "nileCruisesFilter": "Croisières sur le Nil",
    "shoreExcursionsFilter": "Excursions à terre",
    "makeYourTrip": "Organisez votre voyage",
    "specialOffersTitle": "Offres spéciales pour vous",
    "specialOffersDescription": "Trouvez la bonne offre avant qu'il ne soit trop tard",
    "howItWorks": "Comment ça marche ?",
    "howItWorksDescription": "À seulement trois étapes de l'Égypte",
    "findingTitle": "Trouver un voyage",
    "findingDescription": "Sélectionnez votre voyage préféré",
    "bookingTitle": "Réservation",
    "bookingDescription": "Réservation et paiement du voyage",
    "enjoyTitle": "Profiter",
    "enjoyDescription": "Commencez votre voyage passionnant",
    "highlightsTitle": "Points forts de l'Égypte",
    "highlightsDescription": "Découvrez les sites les plus importants d'Égypte",
    "travelBlogs": "Nos blogs de voyage",
    "galleryTitle": "Galerie de voyages passionnants",
    "galleryDescription": "Suivez-nous sur les réseaux sociaux pour voir plus de voyages passionnants",
    "faqTitle": "Questions fréquemment posées",
    "needHelp": "Besoin d'aide pour trouver votre voyage ?",
    "seeMore": "Voir plus",
    "contactNow": "Contacter maintenant",
    "whenTravelling": "Quand voyagez-vous ?",
    "exactTime": "Avoir une date exacte",
    "approximateTime": "Avoir une date approximative",
    "notSureYet": "Pas encore sûr",
    "from": "De",
    "to": "À",
    "selectStartDate": "Sélectionnez la date de début du voyage",
    "selectEndDate": "Sélectionnez la date de fin du voyage",
    "selectMonth": "Sélectionnez un mois",
    "selectExpectedMonth": "Sélectionnez le mois prévu du voyage",
    "manyDays": "Combien de jours",
    "where": "Où",
    "choosePlace": "Choisissez votre lieu préféré en Égypte",
    "howLong": "Combien de temps",
    "chooseDuration": "Combien de jours restez-vous en Égypte",
    "search": "Rechercher",
    "tripType": "Type de voyage ?",
    "oneWay": "Aller simple",
    "roundTrip": "Aller-retour",
    "choosePickup": "Choisissez le lieu de prise en charge",
    "dropoff": "Lieu de dépôt",
    "chooseDropoff": "Choisissez le lieu de dépôt",
    "pickupDate": "Date et heure de prise en charge",
    "choosePickupDate": "Choisissez l'heure et la date de prise en charge",
    "returnDate": "Date et heure de retour",
    "chooseReturnDate": "Choisissez l'heure et la date de retour",
    "sendRequest": "Envoyer une demande",
    "fullName": "Nom complet",
    "nationality": "Nationalité",
    "phone": "Téléphone",
    "upcomingEventsEyebrow": "Événements à venir",
    "upcomingEventsTitle": "Principaux événements et occasions touristiques à venir en Égypte",
    "upcomingEventsDescription": "Découvrez nos derniers événements programmés et rejoignez-nous pour une expérience inoubliable. Réservez votre place dès aujourd'hui !",
    "viewAllEvents": "Voir tous les événements",
    "countdownToday": "Aujourd'hui",
    "countdownTomorrow": "Demain",
    "countdownInDays": "Dans {days} jours",
    "previousEvents": "Événements précédents",
    "nextEvents": "Événements suivants"
  },
  "de": {
    "seasonalTitle": "Unvergessliche Weihnachten in Ägypten",
    "seasonalDescription": "Von den Pyramiden bis zum Nil — Machen Sie diese Festtage unvergesslich",
    "promoTitle": "Buchen Sie eine beliebige Pauschalreise und genießen Sie ein KOSTENLOSES Tourerlebnis ohne zusätzliche Kosten!",
    "promoButton": "Pakete ansehen",
    "heroKicker": "Starten Sie Ihre",
    "heroTitle": "aufregende Reise mit uns",
    "makeTripShort": "Reise planen",
    "findTripShort": "Reise finden",
    "rentCarShort": "Auto mieten",
    "happyCustomer": "Zufriedene Kunden",
    "yearsExperience": "Jahre Erfahrung",
    "totalDestinations": "Reiseziele insgesamt",
    "tripadvisorRating": "Bewertung auf Tripadvisor",
    "whyTravelHeadingBefore": "Warum ",
    "whyTravelHeadingEmphasis": "reisen",
    "whyTravelHeadingAfter": " mit",
    "whyTravelHeadingBrand": "Sun Pyramids Tours?",
    "whyTravelHappyTitle": "Zufriedene Gäste",
    "whyTravelHappyStat": "Über 100.000 Reisende betreut",
    "whyTravelHappyDescription": "Gäste aus aller Welt vertrauen uns bei unvergesslichen Privatreisen, Nilkreuzfahrten und Erlebnissen in Ägypten.",
    "whyTravelExperienceTitle": "Langjährige Erfahrung",
    "whyTravelExperienceStat": "Über 50 Jahre Expertise",
    "whyTravelExperienceDescription": "Ein traditionsreiches lokales Reiseunternehmen, das maßgeschneiderte Ägyptenreisen mit verlässlichem Service und fundierter Zielgebietskenntnis gestaltet.",
    "whyTravelDestinationsTitle": "Reiseziele insgesamt",
    "whyTravelDestinationsStat": "Über 60 Reiseziele und Erlebnisse",
    "whyTravelDestinationsDescription": "Von Kairo und Gizeh über Luxor, Assuan und das Rote Meer bis zu Wüstenausflügen entdecken Sie Ägypten in seiner ganzen Vielfalt.",
    "whyTravelTripadvisorTitle": "Tripadvisor-Bewertung",
    "whyTravelTripadvisorStat": "5,0 Bewertung auf Tripadvisor",
    "whyTravelTripadvisorDescription": "Bestbewertet für Gästebetreuung, Organisation, fachkundige Reiseleiter und unvergessliche Reisemomente in ganz Ägypten.",
    "popularTitle": "Beliebte Reiseziele",
    "popularDescription": "Viele sehr aufregende Orte für Ihren nächsten Urlaub",
    "recommended": "Empfohlen",
    "oneDayFilter": "Tagestouren",
    "multiDaysFilter": "Mehrtägig",
    "nileCruisesFilter": "Nilkreuzfahrten",
    "shoreExcursionsFilter": "Landausflüge",
    "makeYourTrip": "Reise planen",
    "specialOffersTitle": "Sonderangebote für Sie",
    "specialOffersDescription": "Finden Sie das passende Angebot, bevor es zu spät ist",
    "howItWorks": "Wie funktioniert es?",
    "howItWorksDescription": "Nur drei Schritte bis nach Ägypten",
    "findingTitle": "Reise finden",
    "findingDescription": "Wählen Sie Ihre Lieblingsreise",
    "bookingTitle": "Buchung",
    "bookingDescription": "Reise buchen und bezahlen",
    "enjoyTitle": "Genießen",
    "enjoyDescription": "Starten Sie Ihr aufregendes Abenteuer",
    "highlightsTitle": "Highlights Ägyptens",
    "highlightsDescription": "Entdecken Sie die wichtigsten Sehenswürdigkeiten Ägyptens",
    "travelBlogs": "Unsere Reiseblogs",
    "galleryTitle": "Galerie aufregender Reisen",
    "galleryDescription": "Folgen Sie uns in den sozialen Medien, um noch mehr aufregende Reisen zu sehen",
    "faqTitle": "Häufig gestellte Fragen (FAQ)",
    "needHelp": "Hilfe bei der Suche nach Ihrer Reise nötig?",
    "seeMore": "Mehr ansehen",
    "contactNow": "Jetzt kontaktieren",
    "whenTravelling": "Wann werden Sie reisen?",
    "exactTime": "Ich habe ein genaues Datum",
    "approximateTime": "Ich habe einen ungefähren Zeitraum",
    "notSureYet": "Noch nicht sicher",
    "from": "Von",
    "to": "Bis",
    "selectStartDate": "Wählen Sie das Startdatum der Reise",
    "selectEndDate": "Wählen Sie das Enddatum der Reise",
    "selectMonth": "Monat auswählen",
    "selectExpectedMonth": "Wählen Sie den voraussichtlichen Reisemonat",
    "manyDays": "Wie viele Tage",
    "where": "Wohin",
    "choosePlace": "Wählen Sie Ihren Lieblingsort in Ägypten",
    "howLong": "Wie lange",
    "chooseDuration": "Wie viele Tage bleiben Sie in Ägypten",
    "search": "Suchen",
    "tripType": "Art der Reise?",
    "oneWay": "Einfache Fahrt",
    "roundTrip": "Hin- und Rückfahrt",
    "carHolder": "Autovermietung",
    "choosePickup": "Abholort wählen",
    "dropoff": "Rückgabeort",
    "chooseDropoff": "Rückgabeort wählen",
    "pickupDate": "Abholdatum und -uhrzeit",
    "choosePickupDate": "Wählen Sie Datum und Uhrzeit für die Abholung",
    "returnDate": "Rückgabedatum und -uhrzeit",
    "chooseReturnDate": "Wählen Sie Datum und Uhrzeit für die Rückgabe",
    "sendRequest": "Anfrage senden",
    "fullName": "Vollständiger Name",
    "nationality": "Staatsangehörigkeit",
    "phone": "Telefon",
    "upcomingEventsEyebrow": "Kommende Veranstaltungen",
    "upcomingEventsTitle": "Top bevorstehende touristische Veranstaltungen und Anlässe in Ägypten",
    "upcomingEventsDescription": "Entdecken Sie unsere neuesten geplanten Veranstaltungen und begleiten Sie uns zu einem unvergesslichen Erlebnis. Sichern Sie sich noch heute Ihren Platz!",
    "viewAllEvents": "Alle Veranstaltungen ansehen",
    "countdownToday": "Heute",
    "countdownTomorrow": "Morgen",
    "countdownInDays": "In {days} Tagen",
    "previousEvents": "Vorherige Veranstaltungen",
    "nextEvents": "Nächste Veranstaltungen"
  },
  "it": {
    "seasonalTitle": "Un Natale da ricordare in Egitto",
    "seasonalDescription": "Dalle Piramidi al Nilo — Rendi indimenticabile questa festa",
    "promoTitle": "Prenota qualsiasi pacchetto turistico e goditi un’esperienza turistica GRATUITA inclusa senza costi aggiuntivi!",
    "promoButton": "Visualizza pacchetti",
    "heroKicker": "Inizia il tuo",
    "heroTitle": "Emozionante Viaggio con Noi",
    "makeTripShort": "Crea Viaggio",
    "findTripShort": "Trova Viaggio",
    "rentCarShort": "Noleggia Auto",
    "happyCustomer": "Cliente felice",
    "yearsExperience": "Anni di esperienza",
    "totalDestinations": "Destinazioni totali",
    "tripadvisorRating": "Valutazione su Tripadvisor",
    "whyTravelHeadingBefore": "Perché ",
    "whyTravelHeadingEmphasis": "viaggiare",
    "whyTravelHeadingAfter": " con",
    "whyTravelHeadingBrand": "Sun Pyramids Tours?",
    "whyTravelHappyTitle": "Clienti soddisfatti",
    "whyTravelHappyStat": "Oltre 100.000 viaggiatori accompagnati",
    "whyTravelHappyDescription": "Scelti da ospiti di tutto il mondo per tour privati, crociere sul Nilo ed esperienze indimenticabili in Egitto.",
    "whyTravelExperienceTitle": "Anni di esperienza",
    "whyTravelExperienceStat": "Oltre 50 anni di competenza",
    "whyTravelExperienceDescription": "Un’agenzia di viaggi locale di lunga tradizione che crea itinerari su misura in Egitto con un servizio affidabile e una profonda conoscenza delle destinazioni.",
    "whyTravelDestinationsTitle": "Destinazioni totali",
    "whyTravelDestinationsStat": "Oltre 60 destinazioni ed esperienze",
    "whyTravelDestinationsDescription": "Dal Cairo e Giza a Luxor, Assuan, il Mar Rosso e le fughe nel deserto, scopri l’Egitto attraverso esperienze diverse.",
    "whyTravelTripadvisorTitle": "Valutazione Tripadvisor",
    "whyTravelTripadvisorStat": "5,0 su Tripadvisor",
    "whyTravelTripadvisorDescription": "Molto apprezzati per l’assistenza agli ospiti, l’organizzazione, le guide esperte e i momenti di viaggio indimenticabili in tutto l’Egitto.",
    "popularTitle": "Destinazioni Popolari",
    "popularDescription": "Tanti posti emozionanti da visitare per il tuo prossimo viaggio",
    "recommended": "Consigliato",
    "oneDayFilter": "Un giorno",
    "multiDaysFilter": "Più giorni",
    "nileCruisesFilter": "Crociere sul Nilo",
    "shoreExcursionsFilter": "Escursioni a terra",
    "makeYourTrip": "Crea il Tuo Viaggio",
    "specialOffersTitle": "Offerte speciali per te",
    "specialOffersDescription": "Trova l'offerta giusta prima che sia troppo tardi",
    "howItWorks": "Come funziona?",
    "howItWorksDescription": "A solo tre passi dall'Egitto",
    "findingTitle": "Trova Viaggio",
    "findingDescription": "Seleziona il tuo viaggio preferito",
    "bookingTitle": "Prenotazione",
    "bookingDescription": "Prenotazione e pagamento del viaggio",
    "enjoyTitle": "Goditi",
    "enjoyDescription": "Inizia il tuo emozionante viaggio",
    "highlightsTitle": "Punti salienti dell'Egitto",
    "highlightsDescription": "Scopri i luoghi più importanti in Egitto",
    "travelBlogs": "I Nostri Blog di Viaggio",
    "galleryTitle": "Galleria di viaggi emozionanti",
    "galleryDescription": "Seguici sui social per vedere più viaggi emozionanti",
    "faqTitle": "Domande Frequenti",
    "needHelp": "Hai bisogno di aiuto per trovare il tuo viaggio?",
    "seeMore": "Vedi altro",
    "contactNow": "Contatta ora",
    "whenTravelling": "Quando viaggerai?",
    "exactTime": "Hai una data esatta",
    "approximateTime": "Hai una data approssimativa",
    "notSureYet": "Non sono ancora sicuro",
    "from": "Da",
    "to": "A",
    "selectStartDate": "Seleziona la data di inizio del viaggio",
    "selectEndDate": "Seleziona la data di fine del viaggio",
    "selectMonth": "Seleziona Mese",
    "selectExpectedMonth": "Seleziona il mese previsto del viaggio",
    "manyDays": "Quanti Giorni",
    "where": "Dove",
    "choosePlace": "Scegli il tuo posto preferito in Egitto",
    "howLong": "Quanto tempo",
    "chooseDuration": "Quanti giorni rimani in Egitto",
    "search": "Cerca",
    "tripType": "Tipo di viaggio?",
    "oneWay": "Solo andata",
    "roundTrip": "Andata e ritorno",
    "choosePickup": "Scegli luogo di ritiro",
    "dropoff": "Luogo di consegna",
    "chooseDropoff": "Scegli luogo di consegna",
    "pickupDate": "Data e ora di ritiro",
    "choosePickupDate": "Scegli l'ora e la data per il ritiro",
    "returnDate": "Data e ora di ritorno",
    "chooseReturnDate": "Scegli l'ora e la data per il ritorno",
    "sendRequest": "Invia Richiesta",
    "fullName": "Nome completo",
    "nationality": "Nazionalità",
    "phone": "Telefono",
    "upcomingEventsEyebrow": "Prossimi eventi",
    "upcomingEventsTitle": "I migliori eventi e occasioni turistiche imminenti in Egitto",
    "upcomingEventsDescription": "Scopri i nostri ultimi eventi in programma e unisciti a noi per un'esperienza indimenticabile. Prenota il tuo posto oggi stesso!",
    "viewAllEvents": "Visualizza tutti gli eventi",
    "countdownToday": "Oggi",
    "countdownTomorrow": "Domani",
    "countdownInDays": "Tra {days} giorni",
    "previousEvents": "Eventi precedenti",
    "nextEvents": "Eventi successivi"
  },
  "pt": {
    "seasonalTitle": "Um Natal Inesquecível no Egito",
    "seasonalDescription": "Das Pirâmides ao Nilo — Torne esta estação inesquecível",
    "promoTitle": "Reserve qualquer pacote turístico e aproveite uma experiência de passeio GRATUITA incluída sem custo adicional!",
    "promoButton": "Ver pacotes",
    "heroKicker": "Comece sua",
    "heroTitle": "Jornada Empolgante Conosco",
    "makeTripShort": "Criar Viagem",
    "findTripShort": "Encontrar Viagem",
    "rentCarShort": "Alugar Carro",
    "happyCustomer": "Cliente satisfeito",
    "yearsExperience": "Anos de experiência",
    "totalDestinations": "Destinos totais",
    "tripadvisorRating": "Avaliação no Tripadvisor",
    "whyTravelHeadingBefore": "Por que ",
    "whyTravelHeadingEmphasis": "viajar",
    "whyTravelHeadingAfter": " com",
    "whyTravelHeadingBrand": "Sun Pyramids Tours?",
    "whyTravelHappyTitle": "Clientes satisfeitos",
    "whyTravelHappyStat": "Mais de 100 mil viajantes atendidos",
    "whyTravelHappyDescription": "A confiança de viajantes do mundo inteiro em passeios privativos, cruzeiros pelo Nilo e experiências inesquecíveis no Egito.",
    "whyTravelExperienceTitle": "Anos de experiência",
    "whyTravelExperienceStat": "Mais de 50 anos de experiência",
    "whyTravelExperienceDescription": "Uma empresa de turismo local de longa trajetória, criando viagens personalizadas pelo Egito com serviço confiável e profundo conhecimento dos destinos.",
    "whyTravelDestinationsTitle": "Total de destinos",
    "whyTravelDestinationsStat": "Mais de 60 destinos e experiências",
    "whyTravelDestinationsDescription": "Do Cairo e Gizé a Luxor, Assuã, Mar Vermelho e refúgios no deserto, descubra o Egito por meio de experiências variadas.",
    "whyTravelTripadvisorTitle": "Avaliação no Tripadvisor",
    "whyTravelTripadvisorStat": "Nota 5,0 no Tripadvisor",
    "whyTravelTripadvisorDescription": "Muito bem avaliados pelo atendimento aos viajantes, organização, guias especializados e momentos inesquecíveis em todo o Egito.",
    "popularTitle": "Destinos Populares",
    "popularDescription": "Muitos lugares emocionantes para você visitar na sua próxima viagem",
    "recommended": "Recomendado",
    "oneDayFilter": "Um dia",
    "multiDaysFilter": "Vários dias",
    "nileCruisesFilter": "Cruzeiros no Nilo",
    "shoreExcursionsFilter": "Excursões em terra",
    "makeYourTrip": "Faça Sua Viagem",
    "specialOffersTitle": "Ofertas especiais para você",
    "specialOffersDescription": "Encontre a oferta certa antes que seja tarde",
    "howItWorks": "Como funciona?",
    "howItWorksDescription": "A apenas três passos do Egito",
    "findingTitle": "Encontrar Viagem",
    "findingDescription": "Selecione sua viagem favorita",
    "bookingTitle": "Reserva",
    "bookingDescription": "Reserva e pagamento da viagem",
    "enjoyTitle": "Aproveite",
    "enjoyDescription": "Comece sua jornada emocionante",
    "highlightsTitle": "Destaques do Egito",
    "highlightsDescription": "Descubra os marcos mais importantes no Egito",
    "travelBlogs": "Nossos Blogs de Viagem",
    "galleryTitle": "Galeria de jornadas emocionantes",
    "galleryDescription": "Siga-nos nas redes sociais para ver mais jornadas emocionantes",
    "faqTitle": "Perguntas Frequentes",
    "needHelp": "Precisa de ajuda para encontrar sua viagem?",
    "seeMore": "Ver mais",
    "contactNow": "Entrar em contato agora",
    "whenTravelling": "Quando você vai viajar?",
    "exactTime": "Tem um horário exato",
    "approximateTime": "Tem um horário aproximado",
    "notSureYet": "Ainda não tenho certeza",
    "from": "De",
    "to": "Para",
    "selectStartDate": "Selecione a data de início da viagem",
    "selectEndDate": "Selecione a data de término da viagem",
    "selectMonth": "Selecionar Mês",
    "selectExpectedMonth": "Selecione o mês previsto da viagem",
    "manyDays": "Quantos Dias",
    "where": "Onde",
    "choosePlace": "Escolha seu lugar favorito no Egito",
    "howLong": "Quanto tempo",
    "chooseDuration": "Quantos dias você fica no Egito",
    "search": "Pesquisar",
    "tripType": "Tipo de viagem?",
    "oneWay": "Só ida",
    "roundTrip": "Ida e volta",
    "choosePickup": "Escolha local de retirada",
    "dropoff": "Local de entrega",
    "chooseDropoff": "Escolha local de entrega",
    "pickupDate": "Data e hora de retirada",
    "choosePickupDate": "Escolha a hora e data para retirada",
    "returnDate": "Data e hora de retorno",
    "chooseReturnDate": "Escolha a hora e data para retorno",
    "sendRequest": "Enviar Pedido",
    "fullName": "Nome completo",
    "nationality": "Nacionalidade",
    "phone": "Telefone",
    "upcomingEventsEyebrow": "Próximos Eventos",
    "upcomingEventsTitle": "Principais eventos e ocasiões turísticas futuras no Egito",
    "upcomingEventsDescription": "Descubra nossos últimos eventos programados e junte-se a nós para uma experiência inesquecível. Reserve seu lugar hoje mesmo!",
    "viewAllEvents": "Ver todos os eventos",
    "countdownToday": "Hoje",
    "countdownTomorrow": "Amanhã",
    "countdownInDays": "Em {days} dias",
    "previousEvents": "Eventos anteriores",
    "nextEvents": "Próximos eventos"
  },
  "es": {
    "seasonalTitle": "Una Navidad inolvidable en Egipto",
    "seasonalDescription": "De las Pirámides al Nilo: haz que esta época sea inolvidable",
    "promoTitle": "¡Reserva cualquier paquete turístico y disfruta de una experiencia turística GRATIS incluida sin costo adicional!",
    "promoButton": "Ver paquetes",
    "heroKicker": "Comienza tu",
    "heroTitle": "Emocionante viaje con nosotros",
    "makeTripShort": "Organizar Viaje",
    "findTripShort": "Encontrar Viaje",
    "rentCarShort": "Alquilar Coche",
    "happyCustomer": "Clientes felices",
    "yearsExperience": "Años de experiencia",
    "totalDestinations": "Destinos totales",
    "tripadvisorRating": "Valoración en Tripadvisor",
    "whyTravelHeadingBefore": "¿Por qué ",
    "whyTravelHeadingEmphasis": "viajar",
    "whyTravelHeadingAfter": " con",
    "whyTravelHeadingBrand": "Sun Pyramids Tours?",
    "whyTravelHappyTitle": "Clientes felices",
    "whyTravelHappyStat": "Más de 100.000 viajeros atendidos",
    "whyTravelHappyDescription": "La confianza de viajeros de todo el mundo para disfrutar de tours privados, cruceros por el Nilo y experiencias inolvidables en Egipto.",
    "whyTravelExperienceTitle": "Años de experiencia",
    "whyTravelExperienceStat": "Más de 50 años de experiencia",
    "whyTravelExperienceDescription": "Una empresa de viajes local de larga trayectoria que crea recorridos personalizados por Egipto con un servicio fiable y un profundo conocimiento de los destinos.",
    "whyTravelDestinationsTitle": "Destinos totales",
    "whyTravelDestinationsStat": "Más de 60 destinos y experiencias",
    "whyTravelDestinationsDescription": "Desde El Cairo y Guiza hasta Lúxor, Asuán, el mar Rojo y escapadas al desierto, descubre Egipto a través de experiencias diversas.",
    "whyTravelTripadvisorTitle": "Valoración en Tripadvisor",
    "whyTravelTripadvisorStat": "5,0 de valoración en Tripadvisor",
    "whyTravelTripadvisorDescription": "Muy bien valorados por la atención al viajero, la organización, los guías expertos y los momentos inolvidables en todo Egipto.",
    "popularTitle": "Destinos populares",
    "popularDescription": "Muchos lugares emocionantes para visitar en tu próximo viaje",
    "recommended": "Recomendados",
    "oneDayFilter": "Un día",
    "multiDaysFilter": "Varios días",
    "nileCruisesFilter": "Cruceros por el Nilo",
    "shoreExcursionsFilter": "Excursiones en tierra",
    "makeYourTrip": "Organiza tu viaje",
    "specialOffersTitle": "Ofertas especiales para ti",
    "specialOffersDescription": "Encuentra la oferta adecuada antes de que sea demasiado tarde",
    "howItWorks": "¿Cómo funciona?",
    "howItWorksDescription": "A solo tres pasos de Egipto",
    "findingTitle": "Encontrar Viaje",
    "findingDescription": "Selecciona tu viaje favorito",
    "bookingTitle": "Reserva",
    "bookingDescription": "Reserva y pago del viaje",
    "enjoyTitle": "Disfruta",
    "enjoyDescription": "Comienza tu emocionante viaje",
    "highlightsTitle": "Lo más destacado de Egipto",
    "highlightsDescription": "Descubre los monumentos más importantes de Egipto",
    "travelBlogs": "Nuestros blogs de viajes",
    "galleryTitle": "Galería de viajes emocionantes",
    "galleryDescription": "Síguenos en redes sociales para ver más viajes emocionantes",
    "faqTitle": "Preguntas frecuentes",
    "needHelp": "¿Necesitas ayuda para encontrar tu viaje?",
    "seeMore": "Ver más",
    "contactNow": "Contactar ahora",
    "whenTravelling": "¿Cuándo viajarás?",
    "exactTime": "Tengo una fecha exacta",
    "approximateTime": "Tengo una fecha aproximada",
    "notSureYet": "No estoy seguro aún",
    "from": "Desde",
    "to": "Hasta",
    "selectStartDate": "Selecciona la fecha de inicio del viaje",
    "selectEndDate": "Selecciona la fecha de fin del viaje",
    "selectMonth": "Seleccionar mes",
    "selectExpectedMonth": "Selecciona el mes esperado del viaje",
    "manyDays": "¿Cuántos días?",
    "where": "Dónde",
    "choosePlace": "Elige tu lugar favorito en Egipto",
    "howLong": "Cuánto tiempo",
    "chooseDuration": "¿Cuántos días te quedas en Egipto?",
    "search": "Buscar",
    "tripType": "¿Tipo de viaje?",
    "oneWay": "Solo ida",
    "roundTrip": "Ida y vuelta",
    "carHolder": "Titular del coche",
    "choosePickup": "Elige lugar de recogida",
    "dropoff": "Lugar de entrega",
    "chooseDropoff": "Elige lugar de entrega",
    "pickupDate": "Fecha y hora de recogida",
    "choosePickupDate": "Elige la hora y fecha de recogida",
    "returnDate": "Fecha y hora de devolución",
    "chooseReturnDate": "Elige la hora y fecha de devolución",
    "sendRequest": "Enviar solicitud",
    "fullName": "Nombre completo",
    "nationality": "Nacionalidad",
    "phone": "Teléfono",
    "upcomingEventsEyebrow": "Próximos Eventos",
    "upcomingEventsTitle": "Los principales eventos y ocasiones turísticas en Egipto",
    "upcomingEventsDescription": "Descubra nuestros últimos eventos programados y únase a nosotros para vivir una experiencia inolvidable. ¡Reserve su lugar hoy mismo!",
    "viewAllEvents": "Ver todos los eventos",
    "countdownToday": "Hoy",
    "countdownTomorrow": "Mañana",
    "countdownInDays": "En {days} días",
    "previousEvents": "Eventos anteriores",
    "nextEvents": "Próximos eventos"
  },
  "zh": {
    "seasonalTitle": "埃及难忘圣诞之旅",
    "seasonalDescription": "从金字塔到尼罗河 — 让这个节日季成为永恒的记忆",
    "promoTitle": "预订任意旅游套餐，即可免费享受额外赠送的旅游体验，无需额外付费！",
    "promoButton": "查看套餐",
    "heroKicker": "开始您的",
    "heroTitle": "精彩旅程与我们同行",
    "makeTripShort": "定制行程",
    "findTripShort": "查找行程",
    "rentCarShort": "租车",
    "happyCustomer": "满意客户",
    "yearsExperience": "年经验",
    "totalDestinations": "总目的地",
    "tripadvisorRating": "Tripadvisor评分",
    "whyTravelHeadingBefore": "为何与我们一起",
    "whyTravelHeadingEmphasis": "旅行",
    "whyTravelHeadingAfter": "？",
    "whyTravelHeadingBrand": "Sun Pyramids Tours",
    "whyTravelHappyTitle": "满意旅客",
    "whyTravelHappyStat": "已服务超过10万名旅客",
    "whyTravelHappyDescription": "来自世界各地的旅客信赖我们提供难忘的私人游、尼罗河游轮和埃及旅行体验。",
    "whyTravelExperienceTitle": "丰富经验",
    "whyTravelExperienceStat": "50多年专业经验",
    "whyTravelExperienceDescription": "作为一家历史悠久的本地旅行公司，我们凭借可靠服务和深厚的目的地知识，打造量身定制的埃及旅程。",
    "whyTravelDestinationsTitle": "目的地总数",
    "whyTravelDestinationsStat": "60多个目的地与体验",
    "whyTravelDestinationsDescription": "从开罗、吉萨到卢克索、阿斯旺、红海和沙漠秘境，通过多样化体验探索埃及。",
    "whyTravelTripadvisorTitle": "Tripadvisor 评分",
    "whyTravelTripadvisorStat": "Tripadvisor 5.0 分",
    "whyTravelTripadvisorDescription": "我们因贴心服务、周到组织、专业导游以及遍布埃及的难忘旅行时刻而备受好评。",
    "popularTitle": "热门目的地",
    "popularDescription": "为您下次旅行准备的许多令人兴奋的地方",
    "recommended": "推荐",
    "oneDayFilter": "一日游",
    "multiDaysFilter": "多日游",
    "nileCruisesFilter": "尼罗河游轮",
    "shoreExcursionsFilter": "岸上观光",
    "makeYourTrip": "定制您的行程",
    "specialOffersTitle": "为您提供的特别优惠",
    "specialOffersDescription": "在太晚之前找到合适的优惠",
    "howItWorks": "如何运作？",
    "howItWorksDescription": "只需三步即可到达埃及",
    "findingTitle": "查找行程",
    "findingDescription": "选择您喜欢的行程",
    "bookingTitle": "预订",
    "bookingDescription": "行程预订和支付",
    "enjoyTitle": "享受",
    "enjoyDescription": "开始您的精彩旅程",
    "highlightsTitle": "埃及亮点",
    "highlightsDescription": "探索埃及最重要的地标",
    "travelBlogs": "我们的旅行博客",
    "galleryTitle": "精彩旅程画廊",
    "galleryDescription": "关注我们的社交媒体查看更多精彩旅程",
    "faqTitle": "常见问题",
    "needHelp": "需要帮助寻找您的行程吗？",
    "seeMore": "查看更多",
    "contactNow": "立即联系",
    "whenTravelling": "您什么时候旅行？",
    "exactTime": "有确切时间",
    "approximateTime": "有大概时间",
    "notSureYet": "还不确定",
    "from": "从",
    "to": "至",
    "selectStartDate": "选择行程开始日期",
    "selectEndDate": "选择行程结束日期",
    "selectMonth": "选择月份",
    "selectExpectedMonth": "选择预计旅行月份",
    "manyDays": "多少天",
    "where": "哪里",
    "choosePlace": "选择您在埃及最喜欢的地方",
    "howLong": "多长时间",
    "chooseDuration": "您将在埃及停留多少天",
    "search": "搜索",
    "tripType": "行程类型？",
    "oneWay": "单程",
    "roundTrip": "往返",
    "choosePickup": "选择接车地点",
    "dropoff": "下车地点",
    "chooseDropoff": "选择下车地点",
    "pickupDate": "接送日期和时间",
    "choosePickupDate": "选择接送时间和日期",
    "returnDate": "返回日期和时间",
    "chooseReturnDate": "选择返回时间和日期",
    "sendRequest": "发送请求",
    "fullName": "全名",
    "nationality": "国籍",
    "phone": "电话",
    "upcomingEventsEyebrow": "即将举行的活动",
    "upcomingEventsTitle": "埃及即将举行的热门旅游活动与盛会",
    "upcomingEventsDescription": "探索我们最新的日程安排活动，加入我们共度难忘体验。立即预订您的席位！",
    "viewAllEvents": "查看所有活动",
    "countdownToday": "今天",
    "countdownTomorrow": "明天",
    "countdownInDays": "{days} 天后",
    "previousEvents": "上一组活动",
    "nextEvents": "下一组活动"
  }
};

const english = copies.en;

export function homeCopy(locale: Locale): HomeCopy {
  return new Proxy(copies[locale] ?? english, {
    get(target, property: string) {
      return target[property] ?? english[property] ?? property;
    },
  });
}

export function formatEventCountdown(
  days: number | null | undefined,
  copy: HomeCopy,
): string | null {
  if (days === null || days === undefined || days < 0) return null;
  if (days === 0) return copy.countdownToday || "Today";
  if (days === 1) return copy.countdownTomorrow || "Tomorrow";
  const template = copy.countdownInDays || "In {days} days";
  return template.replace("{days}", String(days));
}


