import type { Locale } from "@/types/api";

type UiCopy = Record<string, string>;

const en: UiCopy = {
  home: "Home", oneDay: "One Day Tours", multiDays: "Multi Days Tours", nileCruises: "Nile Cruises",
  shoreExcursions: "Shore Excursion", specialOffer: "Special Offer", rentCar: "Rent Car", about: "About Us",
  contact: "Contact Us", blogs: "Blogs", events: "Events", guide: "Egypt Travel Guide", faqs: "faqs",
  accessible: "Accessible Travel", links: "Sunpyramids Links", contactInfo: "Contact Info", team: "Our Team",
  search: "Search", egyptTours: "Egypt Tours", tours: "Tours", trips: "Tours", cart: "Cart", offers: "Special Offer",
  makeTrip: "Make Your Trip", signIn: "Log in", createAccount: "Create an Account", welcome: "Welcome back",
  forgetPassword: "Did you forget your password?", confirmCode: "Activation code", createPassword: "Create a new password",
  saveLogin: "Save login", agreeTerms: "I agree to the terms and conditions", fullName: "Full Name", email: "Email",
  phone: "Phone", password: "Password", confirmPassword: "Confirm Password", birthDate: "Birthdate",
  nationality: "Nationality", myProfile: "Account Settings", myBookings: "My Bookings", myFavorites: "My Favorites",
  saveChanges: "Save Changes", quickInfo: "Quick information", personalInfo: "Personal information",
  submit: "Submit", addToCart: "ADD TO CART", checkout: "Checkout", subtotal: "Subtotal", oneWay: "One Way",
  roundTrip: "Round Trip", pickup: "Pick Up Date and time", pickupLocation: "Choose Pick-Up Location",
  dropoffLocation: "Choose Drop-Off Location", next: "Next up",
  country: "Country / Region", writeUs: "Write Us....", sendMessage: "Send a Message",
  sending: "Sending...", messageSuccess: "Your message was sent successfully.",
  messageError: "Something went wrong. Please try again.",
  summary: "Payment summary", date: "Date", adults: "Adults", children: "Children", infants: "Infants",
  addOns: "Add-ons", total: "Total", loadingCart: "Loading cart...", emptyCart: "Add tours or car rentals to continue.",
  checkoutLoading: "Creating booking...", card: "Debit / Credit Card", paypal: "PayPal",
  bookTripTitle: "Discover Egypt with Local Experts",
  bookTripDescription: "Explore Egypt’s wonders with tailored tours, expert guidance, and unforgettable memories.",
  whatsappNow: "Whatsapp Now", planYourTrip: "Plan Your Trip", whyChooseUs: "Why Sun Pyramids Tours?",
  licensedTitle: "Licensed Experts", licensedDescription: "Trusted guides with 50+ years experience",
  privateTitle: "Private Transfers", privateDescription: "Comfortable & safe rides throughout Egypt",
  hotelTitle: "Top Hotels", hotelDescription: "Stay at premium hotels with amazing views",
  selectedTours: "Popular Egypt Tours – Handpicked Just for You", makeTripEasy: "Make Your Trip Easy",
  customItinerary: "Get My Custom Itinerary", galleryTitle: "Gallery of Exciting journeys",
  galleryDescription: "Follow us on social media to see more Exciting journeys",
  durationDay: "1 Day", durationDays: "{days} Days",
};

const copies: Record<Locale, UiCopy> = {
  en,
  fr: { home: "Accueil", oneDay: "Tours d'une journée", multiDays: "Tours de plusieurs jours", nileCruises: "Croisières sur le Nil", shoreExcursions: "Excursions à terre", specialOffer: "Offre spéciale", rentCar: "Louer une voiture", about: "À propos", contact: "Contactez-nous", blogs: "Blogs", events: "Événements", accessible: "Voyage accessible", links: "Liens Sunpyramids", contactInfo: "Informations de contact", team: "Notre équipe", search: "Rechercher", egyptTours: "Tours en Égypte", tours: "Tours", trips: "Tours", cart: "Panier", offers: "Offre spéciale", makeTrip: "Organisez votre voyage", signIn: "Se connecter", createAccount: "Créer un compte", welcome: "Content de vous revoir", forgetPassword: "Vous avez oublié votre mot de passe ?", confirmCode: "Code d'activation", createPassword: "Créer un nouveau mot de passe", saveLogin: "Enregistrer la connexion", agreeTerms: "J'accepte les conditions générales", fullName: "Nom complet", email: "E-mail", phone: "Téléphone", password: "Mot de passe", confirmPassword: "Confirmer le mot de passe", nationality: "Nationalité", quickInfo: "Informations rapides", personalInfo: "Informations personnelles", submit: "Soumettre", addToCart: "AJOUTER AU PANIER", checkout: "Passer à la caisse", subtotal: "Sous-total", oneWay: "Aller simple", roundTrip: "Aller-retour", pickup: "Date et heure de prise en charge", pickupLocation: "Choisissez le lieu de prise en charge", dropoffLocation: "Choisissez le lieu de dépôt", next: "À suivre" },
  de: { home: "Startseite", oneDay: "Tagesausflüge", multiDays: "Mehrtägige Rundreisen", nileCruises: "Nilkreuzfahrten", shoreExcursions: "Landausflüge (Kreuzfahrt)", specialOffer: "Sonderangebot", rentCar: "Auto mieten", about: "Über Uns", contact: "Kontakt", blogs: "Blogs", events: "Veranstaltungen", guide: "Ägypten Reiseführer", faqs: "FAQs", accessible: "Barrierefreies Reisen", links: "Sun Pyramids Links", contactInfo: "Kontaktinformationen", team: "Unser Team", search: "Suchen", egyptTours: "Ägypten-Rundreisen", tours: "Rundreisen", trips: "Rundreisen", cart: "Warenkorb", offers: "Sonderangebot", makeTrip: "Reise planen", signIn: "Anmelden", createAccount: "Ein Konto erstellen", welcome: "Willkommen zurück", forgetPassword: "Haben Sie Ihr Passwort vergessen?", confirmCode: "Aktivierungscode", createPassword: "Ein neues Passwort erstellen", saveLogin: "Anmeldung speichern", agreeTerms: "Ich stimme den Allgemeinen Geschäftsbedingungen", fullName: "Vollständiger Name", email: "E-Mail", phone: "Telefon", password: "Passwort", confirmPassword: "Passwort bestätigen", birthDate: "Geburtsdatum", nationality: "Staatsangehörigkeit", myProfile: "Kontoeinstellungen", myBookings: "Meine Buchungen", myFavorites: "Meine Favoriten", saveChanges: "Änderungen speichern", quickInfo: "Kurzinformation", personalInfo: "Persönliche Daten", submit: "Absenden", addToCart: "IN DEN WARENKORB", checkout: "Zur Kasse", subtotal: "Zwischensumme", oneWay: "Einfache Fahrt", roundTrip: "Hin- und Rückfahrt", pickup: "Abholdatum und -uhrzeit", pickupLocation: "Abholort wählen", dropoffLocation: "Rückgabeort wählen", next: "Als nächstes" },
  it: { home: "Home", oneDay: "Tour di un giorno", multiDays: "Tour di più giorni", nileCruises: "Crociere sul Nilo", shoreExcursions: "Escursioni a terra", specialOffer: "Offerta Speciale", rentCar: "Noleggia Auto", about: "Chi Siamo", contact: "Contatti", blogs: "Blog", events: "Eventi", accessible: "Viaggio accessibile", links: "Collegamenti Sunpyramids", contactInfo: "Informazioni di contatto", team: "Il Nostro Team", search: "Cerca", egyptTours: "Tour in Egitto", tours: "Tour", trips: "Tour", cart: "Carrello", offers: "Offerta Speciale", makeTrip: "Crea il Tuo Viaggio", signIn: "Accedi", createAccount: "Crea un Account", welcome: "Bentornato", forgetPassword: "Hai dimenticato la password?", confirmCode: "Codice di attivazione", createPassword: "Crea una nuova password", saveLogin: "Salva accesso", agreeTerms: "Accetto i termini e condizioni", fullName: "Nome completo", email: "Email", phone: "Telefono", password: "Password", confirmPassword: "Conferma password", nationality: "Nazionalità", quickInfo: "Informazioni rapide", personalInfo: "Informazioni personali", submit: "Invia", addToCart: "AGGIUNGI AL CARRELLO", checkout: "Acquista", subtotal: "Subtotale", oneWay: "Solo andata", roundTrip: "Andata e ritorno", pickup: "Data e ora di ritiro", pickupLocation: "Scegli luogo di ritiro", dropoffLocation: "Scegli luogo di consegna", next: "Prossimo passo" },
  pt: { home: "Início", oneDay: "Passeios de um dia", multiDays: "Passeios de vários dias", nileCruises: "Cruzeiros no Nilo", shoreExcursions: "Excursões em terra", specialOffer: "Oferta Especial", rentCar: "Alugar Carro", about: "Sobre Nós", contact: "Contato", blogs: "Blogs", events: "Eventos", accessible: "Viagem acessível", links: "Links Sunpyramids", contactInfo: "Informações de contato", team: "Nosso Time", search: "Pesquisar", egyptTours: "Passeios no Egito", tours: "Passeios", trips: "Passeios", cart: "Carrinho", offers: "Oferta Especial", makeTrip: "Faça Sua Viagem", signIn: "Entrar", createAccount: "Criar uma Conta", welcome: "Bem-vindo de volta", forgetPassword: "Esqueceu sua senha?", confirmCode: "Código de ativação", createPassword: "Criar nova senha", saveLogin: "Salvar login", agreeTerms: "Eu concordo com os termos e condições", fullName: "Nome completo", email: "Email", phone: "Telefone", password: "Senha", confirmPassword: "Confirmar senha", nationality: "Nacionalidade", quickInfo: "Informações rápidas", personalInfo: "Informações pessoais", submit: "Enviar", addToCart: "ADICIONAR AO CARRINHO", checkout: "Finalizar compra", subtotal: "Subtotal", oneWay: "Só ida", roundTrip: "Ida e volta", pickup: "Data e hora de retirada", pickupLocation: "Escolha local de retirada", dropoffLocation: "Escolha local de entrega", next: "Próximo passo" },
  es: { home: "Inicio", oneDay: "Tours de un día", multiDays: "Tours de varios días", nileCruises: "Cruceros por el Nilo", shoreExcursions: "Excursiones en tierra", specialOffer: "Oferta especial", rentCar: "Alquilar coche", about: "Sobre Nosotros", contact: "Contacto", blogs: "Blogs", events: "Eventos", guide: "Guía de Viaje de Egipto", faqs: "preguntas frecuentes", accessible: "Viaje accesible", links: "Enlaces de Sunpyramids", contactInfo: "Información de contacto", team: "Nuestro equipo", search: "Buscar", egyptTours: "Tours por Egipto", tours: "Tours", trips: "Tours", cart: "Carrito", offers: "Oferta especial", makeTrip: "Organiza tu viaje", signIn: "Iniciar sesión", createAccount: "Crear una cuenta", welcome: "Bienvenido de nuevo", forgetPassword: "¿Olvidaste tu contraseña?", confirmCode: "Código de activación", createPassword: "Crear una nueva contraseña", saveLogin: "Guardar inicio de sesión", agreeTerms: "Acepto los términos y condiciones", fullName: "Nombre completo", email: "Correo electrónico", phone: "Teléfono", password: "Contraseña", confirmPassword: "Confirmar contraseña", birthDate: "Fecha de nacimiento", nationality: "Nacionalidad", myProfile: "Configuración de la cuenta", myBookings: "Mis Reservas", myFavorites: "Mis Favoritos", saveChanges: "Guardar cambios", quickInfo: "Información rápida", personalInfo: "Información personal", submit: "Enviar", addToCart: "AÑADIR AL CARRITO", checkout: "Pagar", subtotal: "Subtotal", oneWay: "Solo ida", roundTrip: "Ida y vuelta", pickup: "Fecha y hora de recogida", pickupLocation: "Elige lugar de recogida", dropoffLocation: "Elige lugar de entrega", next: "Próximo paso" },
  zh: { home: "首页", oneDay: "一日游", multiDays: "多日游", nileCruises: "尼罗河游轮", shoreExcursions: "岸上观光", specialOffer: "特别优惠", rentCar: "租车", about: "关于我们", contact: "联系我们", blogs: "博客", events: "活动", faqs: "常見問題", accessible: "无障碍旅行", links: "Sunpyramids链接", contactInfo: "联系信息", team: "我们的团队", search: "搜索", egyptTours: "埃及旅游", tours: "旅游", trips: "旅游", cart: "购物车", offers: "特别优惠", makeTrip: "定制您的行程", signIn: "登录", createAccount: "创建账户", welcome: "欢迎回来", forgetPassword: "忘记密码了吗？", confirmCode: "激活码", createPassword: "创建新密码", saveLogin: "保存登录", agreeTerms: "我同意条款和条件", fullName: "全名", email: "电子邮件", phone: "电话", password: "密码", confirmPassword: "确认密码", nationality: "国籍", quickInfo: "快速信息", personalInfo: "个人信息", submit: "提交", addToCart: "加入购物车", checkout: "结账", subtotal: "小计", oneWay: "单程", roundTrip: "往返", pickup: "接送日期和时间", pickupLocation: "选择接车地点", dropoffLocation: "选择下车地点", next: "下一步" },
};

// Confirmed from the original Nuxt inputLabels dictionaries.
const formCopies: Record<Locale, UiCopy> = {
  en: { country: "Country / Region", writeUs: "Write Us....", sendMessage: "Send a Message", sending: "Sending...", signOut: "Sign out", exploreTours: "Explore Tours", clearAll: "Clear all", apply: "Apply", state: "State", note: "Note", saveEdits: "Save Edits", delete: "Delete", discount: "Discount", addCouponCode: "Add Coupon code..", checkoutNow: "Checkout Now", billingDetails: "Billing Details", paymentMethod: "Payment Method", paymentSuccess: "Payment Successfully", paymentPending: "Payment Pending", paymentFailed: "Your Payment has been failed", back: "Back", durationDay: "1 Day", durationDays: "{days} Days" },
  fr: { country: "Pays / Région", writeUs: "Écrivez-nous....", sendMessage: "Envoyer un message", sending: "Envoi...", signOut: "Se déconnecter", exploreTours: "Explorer les tours", clearAll: "Tout effacer", apply: "Appliquer", state: "État", note: "Note", saveEdits: "Enregistrer les modifications", delete: "Supprimer", discount: "Réduction", addCouponCode: "Ajouter un code coupon..", checkoutNow: "Passer à la caisse maintenant", billingDetails: "Détails de facturation", paymentMethod: "Méthode de paiement", back: "Retour", summary: "Résumé du paiement", date: "Date", adults: "Adultes", children: "Enfants", infants: "Bébés", addOns: "Suppléments", total: "Total", loadingCart: "Chargement du panier...", emptyCart: "Ajoutez des circuits ou des locations de voiture pour continuer.", checkoutLoading: "Création de la réservation...", card: "Carte de débit / crédit", bookTripTitle: "Découvrez l'Égypte avec des Experts Locaux", bookTripDescription: "Explorez les merveilles de l'Égypte avec des circuits sur mesure, des guides experts et des souvenirs inoubliables.", whatsappNow: "WhatsApp Maintenant", planYourTrip: "Planifiez Votre Voyage", whyChooseUs: "Pourquoi Choisir Sun Pyramids Tours?", licensedTitle: "Experts Agréés", licensedDescription: "Guides de confiance avec plus de 50 ans d'expérience", privateTitle: "Transferts Privés", privateDescription: "Trajets confortables et sécurisés à travers l'Égypte", hotelTitle: "Meilleurs Hôtels", hotelDescription: "Séjour dans des hôtels premium avec des vues magnifiques", selectedTours: "Circuits Populaires en Égypte – Sélectionnés pour Vous", makeTripEasy: "Facilitez Votre Voyage", customItinerary: "Obtenez Mon Itinéraire Personnalisé", galleryTitle: "Galerie de voyages passionnants", galleryDescription: "Suivez-nous sur les réseaux sociaux pour voir plus de voyages passionnants", durationDay: "1 Jour", durationDays: "{days} Jours" },
  de: { country: "Land / Region", writeUs: "Schreiben Sie uns....", sendMessage: "Nachricht senden", sending: "Wird gesendet...", signOut: "Abmelden", exploreTours: "Rundreisen entdecken", clearAll: "Alle löschen", apply: "Übernehmen", state: "Bundesland / Region", note: "Notiz", saveEdits: "Änderungen speichern", delete: "Löschen", discount: "Rabatt", addCouponCode: "Rabattcode hinzufügen..", checkoutNow: "Jetzt zur Kasse", billingDetails: "Rechnungsdaten", paymentMethod: "Zahlungsmethode", paymentSuccess: "Zahlung erfolgreich", paymentPending: "Zahlung ausstehend", paymentFailed: "Ihre Zahlung ist fehlgeschlagen", back: "Zurück", summary: "Zahlungsübersicht", date: "Datum", adults: "Erwachsene", children: "Kinder", infants: "Kleinkinder", addOns: "Zusatzleistungen", total: "Gesamt", loadingCart: "Warenkorb wird geladen...", emptyCart: "Fügen Sie Rundreisen oder Mietwagen hinzu, um fortzufahren.", checkoutLoading: "Buchung wird erstellt...", card: "Debit-/Kreditkarte", bookTripTitle: "Entdecken Sie Ägypten mit lokalen Experten", bookTripDescription: "Erkunden Sie die Wunder Ägyptens mit maßgeschneiderten Reisen, fachkundiger Führung und unvergesslichen Erinnerungen.", whatsappNow: "Jetzt per WhatsApp", planYourTrip: "Reise Planen", whyChooseUs: "Warum Sun Pyramids Tours?", licensedTitle: "Lizenzierte Experten", licensedDescription: "Vertrauenswürdige Reiseleiter mit über 50 Jahren Erfahrung", privateTitle: "Private Transfers", privateDescription: "Komfortable & sichere Fahrten durch ganz Ägypten", hotelTitle: "Top-Hotels", hotelDescription: "Übernachten Sie in Premium-Hotels mit fantastischer Aussicht", selectedTours: "Beliebte Ägypten-Rundreisen – Handverlesen für Sie", makeTripEasy: "Gestalten Sie Ihre Reise einfach", customItinerary: "Meine individuelle Reiseroute erhalten", galleryTitle: "Galerie aufregender Reisen", galleryDescription: "Folgen Sie uns in den sozialen Medien, um noch mehr aufregende Reisen zu sehen", durationDay: "1 Tag", durationDays: "{days} Tage" },
  it: { country: "Paese / Regione", writeUs: "Scrivici....", sendMessage: "Invia un messaggio", sending: "Invio...", signOut: "Esci", exploreTours: "Esplora Tour", clearAll: "Cancella tutto", apply: "Applica", state: "Stato", note: "Nota", saveEdits: "Salva modifiche", delete: "Elimina", discount: "Sconto", addCouponCode: "Aggiungi codice coupon..", checkoutNow: "Procedi all'acquisto", billingDetails: "Dettagli di fatturazione", paymentMethod: "Metodo di pagamento", back: "Indietro", summary: "Riepilogo pagamento", date: "Data", adults: "Adulti", children: "Bambini", infants: "Neonati", addOns: "Extra", total: "Totale", loadingCart: "Caricamento del carrello...", emptyCart: "Aggiungi tour o noleggi auto per continuare.", checkoutLoading: "Creazione della prenotazione...", card: "Carta di debito / credito", bookTripTitle: "Scopri l'Egitto con Esperti Locali", bookTripDescription: "Esplora le meraviglie dell'Egitto con tour personalizzati, guide esperte e ricordi indimenticabili.", whatsappNow: "WhatsApp Ora", planYourTrip: "Pianifica il Tuo Viaggio", whyChooseUs: "Perché Scegliere Sun Pyramids Tours?", licensedTitle: "Esperti Autorizzati", licensedDescription: "Guide fidate con oltre 50 anni di esperienza", privateTitle: "Trasferimenti Privati", privateDescription: "Viaggi comodi e sicuri in tutto l'Egitto", hotelTitle: "Migliori Hotel", hotelDescription: "Soggiorno in hotel premium con viste mozzafiato", selectedTours: "Tour Popolari in Egitto – Selezionati per Te", makeTripEasy: "Rendi il Tuo Viaggio Facile", customItinerary: "Ottieni il Mio Itinerario Personalizzato", galleryTitle: "Galleria di viaggi emozionanti", galleryDescription: "Seguici sui social per vedere più viaggi emozionanti", durationDay: "1 Giorno", durationDays: "{days} Giorni" },
  pt: { country: "País/Região", writeUs: "Escreva para nós....", sendMessage: "Enviar mensagem", sending: "Enviando...", signOut: "Sair", exploreTours: "Explorar Passeios", clearAll: "Limpar tudo", apply: "Aplicar", state: "Estado", note: "Observação", saveEdits: "Salvar edições", delete: "Excluir", discount: "Desconto", addCouponCode: "Adicionar código de cupom..", checkoutNow: "Finalizar compra agora", billingDetails: "Detalhes de faturamento", paymentMethod: "Método de pagamento", back: "Voltar", summary: "Resumo do pagamento", date: "Data", adults: "Adultos", children: "Crianças", infants: "Bebês", addOns: "Adicionais", total: "Total", loadingCart: "Carregando o carrinho...", emptyCart: "Adicione passeios ou aluguéis de carro para continuar.", checkoutLoading: "Criando reserva...", card: "Cartão de débito / crédito", bookTripTitle: "Descubra o Egito com Especialistas Locais", bookTripDescription: "Explore as maravilhas do Egito com roteiros personalizados, orientação especializada e memórias inesquecíveis.", whatsappNow: "WhatsApp Agora", planYourTrip: "Planeje Sua Viagem", whyChooseUs: "Por Que Escolher Sun Pyramids Tours?", licensedTitle: "Especialistas Licenciados", licensedDescription: "Guias confiáveis com mais de 50 anos de experiência", privateTitle: "Transferes Privados", privateDescription: "Viagens confortáveis e seguras por todo o Egito", hotelTitle: "Melhores Hotéis", hotelDescription: "Hospedagem em hotéis premium com vistas incríveis", selectedTours: "Passeios Populares no Egito – Selecionados para Você", makeTripEasy: "Facilite Sua Viagem", customItinerary: "Obtenha Meu Itinerário Personalizado", galleryTitle: "Galeria de jornadas emocionantes", galleryDescription: "Siga-nos nas redes sociais para ver mais jornadas emocionantes", durationDay: "1 Dia", durationDays: "{days} Dias" },
  es: { country: "País / Región", writeUs: "Escríbenos....", sendMessage: "Enviar un mensaje", sending: "Enviando...", signOut: "Cerrar sesión", exploreTours: "Explorar Tours", clearAll: "Limpiar todo", apply: "Aplicar", state: "Estado", note: "Nota", saveEdits: "Guardar cambios", delete: "Eliminar", discount: "Descuento", addCouponCode: "Añadir código de cupón..", checkoutNow: "Pagar ahora", billingDetails: "Detalles de facturación", paymentMethod: "Método de pago", paymentSuccess: "Pago exitoso", paymentPending: "Pago pendiente", paymentFailed: "Tu pago ha fallado", back: "Atrás", summary: "Resumen de pago", date: "Fecha", adults: "Adultos", children: "Niños", infants: "Bebés", addOns: "Extras", total: "Total", loadingCart: "Cargando el carrito...", emptyCart: "Añade tours o alquileres de coches para continuar.", checkoutLoading: "Creando la reserva...", card: "Tarjeta de débito / crédito", bookTripTitle: "Descubre Egipto con Expertos Locales", bookTripDescription: "Explora las maravillas de Egipto con tours personalizados, guías expertos y recuerdos inolvidables.", whatsappNow: "WhatsApp Ahora", planYourTrip: "Planifica Tu Viaje", whyChooseUs: "¿Por Qué Elegir Sun Pyramids Tours?", licensedTitle: "Expertos Certificados", licensedDescription: "Guías de confianza con más de 50 años de experiencia", privateTitle: "Traslados Privados", privateDescription: "Viajes cómodos y seguros por todo Egipto", hotelTitle: "Hoteles de Primera", hotelDescription: "Alojamiento en hoteles premium con vistas increíbles", selectedTours: "Tours Populares en Egipto – Seleccionados para Ti", makeTripEasy: "Haz Tu Viaje Más Fácil", customItinerary: "Obtén Mi Itinerario Personalizado", galleryTitle: "Galería de viajes emocionantes", galleryDescription: "Síguenos en redes sociales para ver más viajes emocionantes", durationDay: "1 Día", durationDays: "{days} Días" },
  zh: { country: "国家/地区", writeUs: "给我们留言....", sendMessage: "发送消息", sending: "发送中...", signOut: "退出登录", exploreTours: "探索旅游", clearAll: "全部清除", apply: "应用", state: "州/省", note: "备注", saveEdits: "保存编辑", delete: "删除", discount: "折扣", addCouponCode: "添加优惠码..", checkoutNow: "立即结账", billingDetails: "账单详情", paymentMethod: "付款方式", back: "返回", summary: "付款摘要", date: "日期", adults: "成人", children: "儿童", infants: "婴儿", addOns: "附加服务", total: "总计", loadingCart: "正在加载购物车...", emptyCart: "添加旅游或租车以继续。", checkoutLoading: "正在创建预订...", card: "借记卡 / 信用卡", bookTripTitle: "与当地专家一起探索埃及", bookTripDescription: "通过定制行程、专业导游和难忘的回忆，探索埃及的奇迹。", whatsappNow: "立即WhatsApp", planYourTrip: "计划您的旅程", whyChooseUs: "为什么选择Sun Pyramids Tours？", licensedTitle: "持证专家", licensedDescription: "值得信赖的导游，拥有50多年经验", privateTitle: "私人接送", privateDescription: "舒适安全的埃及全程交通", hotelTitle: "顶级酒店", hotelDescription: "入住景观极佳的豪华酒店", selectedTours: "热门埃及之旅——专为您精选", makeTripEasy: "让您的旅行更轻松", customItinerary: "获取我的定制行程", galleryTitle: "精彩旅程画廊", galleryDescription: "关注我们的社交媒体查看更多精彩旅程", durationDay: "1天", durationDays: "{days}天" },
};

export function uiCopy(locale: Locale): UiCopy {
  return new Proxy({ ...en, ...(copies[locale] ?? {}), ...formCopies[locale] }, {
    get(target, property: string) {
      return target[property] ?? en[property] ?? property;
    },
  });
}
